## Merge Judicial Autonomy and V-Dem Datasets

In [35]:
import yaml

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
try:
    with open('../config.yaml') as file:
        config = yaml.safe_load(file)
except:
    print("Yaml file not found.")

### 1. Load datasets (raw data)

In [11]:
# DELETE?

# Import cleaning functions

import sys
sys.path.append('../py_files')
from functions import cleaning_judicial_autonomy_data
from functions import cleaning_vdem_ert_data

In [12]:
# Load and clean Judicial Autonomy Dataset
q1_df = pd.read_csv(config['input_data']['q1_dataset'])
q1_cleaned = cleaning_judicial_autonomy_data(q1_df) 
q1_cleaned.head()

,username,country,country_code,year,q1c1_apjuac,q1c1_apjufc,q1c1_apjuhc,q1c1_appealac,q1c1_appealfc,q1c1_appealhc,...,q1c3_sanctscale,q1c4_casealloc,q1c4_competence,q1c4_manbudget,q1c4_reasondecis,q1c4_regbudget,q1c4_sameright,q1c4_whochair,q1c4_whocharge,q1c4_whoselect
46,ALB33wGG5n,Albania,ALA,2000,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
47,ALB33wGG5n,Albania,ALA,2001,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
48,ALB33wGG5n,Albania,ALA,2002,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
49,ALB33wGG5n,Albania,ALA,2003,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
50,ALB33wGG5n,Albania,ALA,2004,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5

In [21]:
# Load and clean V-Dem Episodes of Regime Transformation Dataset
vdem_df = pd.read_csv(config['input_data']['vdem_episodes_of_regime_transformation_dataset'])
vdem_cleaned = cleaning_vdem_ert_data(vdem_df)

vdem_cleaned
vdem_cleaned.head()

,country,year,reg_id,reg_type,v2x_regime,v2x_polyarchy,reg_trans,row_regch_event,dem_ep
348,Sweden,2000,SWE_1921_2023,1.0,3.0,0.914,0.0,0.0,0
349,Sweden,2001,SWE_1921_2023,1.0,3.0,0.914,0.0,0.0,0
350,Sweden,2002,SWE_1921_2023,1.0,3.0,0.914,0.0,0.0,0
351,Sweden,2003,SWE_1921_2023,1.0,3.0,0.915,0.0,0.0,0
352,Sweden,2004,SWE_1921_2023,1.0,3.0,0.915,0.0,0.0,0

In [ ]:
# Clean datasets

### 1. Load Datasets (clean data)

In [22]:
# Load and clean Judicial Autonomy Dataset (index and macro-indicator)

q1_index_macro = pd.read_csv(config['output_data']['q1_output_index_macro'])
#q1_index_macro

In [23]:
# Load and clean Judicial Autonomy Dataset (index, macro-indicator and micro-indicator)

q1_index_macro_micro = pd.read_csv(config['output_data']['q1_output_index_macro_micro'])
#q1_index_macro_micro

### 2. Merge datasets

In [1]:
# Merge Judicial Autonomy index and macro-indicators subset & V-Dem ERT dataset

q1_index_macro_vdem = pd.merge(q1_index_macro, vdem_cleaned, how='outer', on=['country', 'year'])

# Export dataset
q1_index_macro_vdem.to_csv(config['output_data']['q1_output_index_macro_vdem'])

# View dataset
q1_index_macro_vdem

NameError: name 'pd' is not defined

In [2]:
# Merge Judicial Autonomy index, macro- and micro-indicators subset & V-Dem ERT dataset

q1_index_macro_micro_vdem = pd.merge(q1_index_macro_micro, vdem_cleaned, how='outer', on=['country', 'year'])

# Export dataset
q1_index_macro_micro_vdem.to_csv(config['output_data']['q1_output_index_macro_micro_vdem'])

#View dataset
q1_index_macro_micro_vdem

NameError: name 'pd' is not defined

In [29]:
# Check data types
q1_index_macro_vdem.dtypes

Unnamed: 0                                         int64
country                                           object
year                                               int64
country_year                                      object
index_measure                                    float64
q1_macro_appointment_procedures_ind_measure      float64
q1_macro_selection_criteria_ind_measure          float64
q1_macro_professional_rights_ind_measure         float64
q1_macro_professional_obligations_ind_measure    float64
q1_macro_judicial_administration_ind_measure     float64
reg_id                                            object
reg_type                                         float64
v2x_regime                                       float64
v2x_polyarchy                                    float64
reg_trans                                        float64
row_regch_event                                  float64
dem_ep                                             int64
dtype: object