## Merge Judicial Autonomy and V-Dem Datasets

In [5]:
import yaml

import pandas as pd
import numpy as np

In [6]:
try:
    with open('../config.yaml') as file:
        config = yaml.safe_load(file)
except:
    print("Yaml file not found.")

### 1. Load Datasets (using clean datasets; incl. missing values)

In [7]:
q1_cleaned = pd.read_csv(config['output_data']['q1_dataset'])
q1_cleaned

,username,country,country_code,year,q1c1_apjuac,q1c1_apjufc,q1c1_apjuhc,q1c1_appealac,q1c1_appealfc,q1c1_appealhc,...,q1c3_sanctscale,q1c4_casealloc,q1c4_competence,q1c4_manbudget,q1c4_reasondecis,q1c4_regbudget,q1c4_sameright,q1c4_whochair,q1c4_whocharge,q1c4_whoselect
0,ALB33wGG5n,Albania,ALA,2000,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.00,1.0,0.0,1.0,0.0,NaN,0.5,0.5
1,ALB33wGG5n,Albania,ALA,2001,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.00,1.0,0.0,1.0,0.0,NaN,0.5,0.5
2,ALB33wGG5n,Albania,ALA,2002,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.00,1.0,0.0,1.0,0.0,NaN,0.5,0.5
3,ALB33wGG5n,Albania,ALA,2003,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.00,1.0,0.0,1.0,0.0,NaN,0.5,0.5
4,ALB33wGG5n,Albania,ALA,2004,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.00,1.0,0.0,1.0,0.0,NaN,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,UKR22Gf5Kx,Ukraine,UKR,2018,0.5,0.5,0.5,1.0,1.0,1.0,...,1.0,0.5,0.67,0.0,0.0,0.0,1.0,1.0,1.0,1.0
916,UKR22Gf5Kx,Ukraine,UKR,2019,0.5,0.5,0.5,1.0,1.0,1.0,...,1.0,0.5,0.67,0.0,0.0,0.0,1.0,1.0,1.0,1.0
917,UKR22Gf5Kx,Ukraine,UKR,2020,0.5,0.5,0.5,1.0,1.0,1.0,...,1.0,0.5,0.67,0.0,0.0,0.0,1.0,1.0,1.0,1.0
918,UKR22Gf5Kx,Ukraine,UKR,2021,0.5,0.5,0.5,1.0,1.0,1.0,...,1.0,0.5,0.67,0.0,0.0,0.0,1.0,1.0,1.0,1.0
919,UKR22Gf5Kx,Ukraine,UKR,2022,0.5,0.5,0.5,1.0,1.0,1.0,...,1.0,0.5,0.67,0.0,0.0,0.0,1.0,1.0,1.0,1.0

In [7]:
# Load clean Judicial Autonomy Dataset (index and macro indicator)

q1_index_macro = pd.read_csv(config['output_data']['q1_output_index_macro'])
#q1_index_macro

In [8]:
# Load clean Judicial Autonomy Dataset (index, macro and micro indicators)

q1_index_macro_micro = pd.read_csv(config['output_data']['q1_output_index_macro_micro'])
#q1_index_macro_micro

### 2. Alternative (load datasets based on raw data, using cleaning functions; incl. missing values)

In [11]:
# Import cleaning functions
import sys
sys.path.append('../py_files')
from functions import cleaning_judicial_autonomy_data
from functions import cleaning_vdem_ert_data

In [12]:
# Load and clean raw Judicial Autonomy Dataset
q1_df = pd.read_csv(config['input_data']['q1_dataset'])
q1_cleaned = cleaning_judicial_autonomy_data(q1_df) 
q1_cleaned.head()

,username,country,country_code,year,q1c1_apjuac,q1c1_apjufc,q1c1_apjuhc,q1c1_appealac,q1c1_appealfc,q1c1_appealhc,...,q1c3_sanctscale,q1c4_casealloc,q1c4_competence,q1c4_manbudget,q1c4_reasondecis,q1c4_regbudget,q1c4_sameright,q1c4_whochair,q1c4_whocharge,q1c4_whoselect
46,ALB33wGG5n,Albania,ALA,2000,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
47,ALB33wGG5n,Albania,ALA,2001,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
48,ALB33wGG5n,Albania,ALA,2002,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
49,ALB33wGG5n,Albania,ALA,2003,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5
50,ALB33wGG5n,Albania,ALA,2004,0.5,0.5,0.0,0.0,0.0,0.0,...,0.5,1.0,0.0,1.0,0.0,1.0,0.0,NaN,0.5,0.5

In [5]:
# Load and clean V-Dem Episodes of Regime Transformation Dataset
vdem_df = pd.read_csv(config['input_data']['vdem_episodes_of_regime_transformation_dataset'])
vdem_cleaned = cleaning_vdem_ert_data(vdem_df)

vdem_cleaned
vdem_cleaned.head()

,country,year,reg_id,reg_type,v2x_regime,v2x_polyarchy,reg_trans,row_regch_event,dem_ep
348,Sweden,2000,SWE_1921_2023,1.0,3.0,0.914,0.0,0.0,0
349,Sweden,2001,SWE_1921_2023,1.0,3.0,0.914,0.0,0.0,0
350,Sweden,2002,SWE_1921_2023,1.0,3.0,0.914,0.0,0.0,0
351,Sweden,2003,SWE_1921_2023,1.0,3.0,0.915,0.0,0.0,0
352,Sweden,2004,SWE_1921_2023,1.0,3.0,0.915,0.0,0.0,0

In [6]:
# Clean datasets

### 2. Merge datasets

In [10]:
# Merge Judicial Autonomy index and macro-indicators subset & V-Dem dataset

q1_index_macro_vdem = pd.merge(q1_index_macro, vdem_cleaned, how='outer', on=['country', 'year'])

# Export dataset
q1_index_macro_vdem.to_csv(config['output_data']['q1_output_index_macro_vdem'])

# View dataset
q1_index_macro_vdem

,Unnamed: 0,country,year,country_year,index_measure,q1_macro_appointment_procedures_ind_measure,q1_macro_selection_criteria_ind_measure,q1_macro_professional_rights_ind_measure,q1_macro_professional_obligations_ind_measure,q1_macro_judicial_administration_ind_measure,reg_id,reg_type,v2x_regime,v2x_polyarchy,reg_trans,row_regch_event,dem_ep
0,0,Albania,2000,Albania_2000,0.52,0.55,0.50,0.42,0.65,0.50,ALB_1914_2004,0.0,1.0,0.407,0.0,0.0,1
1,1,Albania,2001,Albania_2001,0.52,0.55,0.50,0.42,0.65,0.50,ALB_1914_2004,0.0,1.0,0.440,0.0,0.0,1
2,2,Albania,2002,Albania_2002,0.52,0.55,0.50,0.42,0.65,0.50,ALB_1914_2004,0.0,1.0,0.484,0.0,0.0,1
3,3,Albania,2003,Albania_2003,0.52,0.55,0.50,0.42,0.65,0.50,ALB_1914_2004,0.0,1.0,0.490,0.0,0.0,1
4,4,Albania,2004,Albania_2004,0.55,0.55,0.50,0.42,0.76,0.50,ALB_1914_2004,0.0,1.0,0.490,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,915,United Kingdom,2018,United Kingdom_2018,0.62,0.33,0.89,0.83,0.33,0.74,GBR_1919_2023,1.0,3.0,0.875,0.0,0.0,0
916,916,United Kingdom,2019,United Kingdom_2019,0.62,0.33,0.89,0.83,0.33,0.74,GBR_1919_2023,1.0,3.0,0.857,0.0,0.0,0
917,917,United Kingdom,2020,United Kingdom_2020,0.62,0.33,0.89,0.83,0.33,0.74,GBR_1919_2023,1.0,3.0,0.874,0.0,0.0,0
918,918,United Kingdom,2021,United Kingdom_2021,0.62,0.33,0.89,0.83,0.33,0.74,GBR_1919_2023,1.0,3.0,0.864,0.0,0.0,0
919,919,United Kingdom,2022,United Kingdom_2022,0.62,0.33,0.89,0.83,0.33,0.74,GBR_1919_2023,1.0,3.0,0.843,0.0,0.0,0

In [11]:
# Merge Judicial Autonomy index, macro- and micro-indicators subset & V-Dem dataset

q1_index_macro_micro_vdem = pd.merge(q1_index_macro_micro, vdem_cleaned, how='outer', on=['country', 'year'])

# Export dataset
q1_index_macro_micro_vdem.to_csv(config['output_data']['q1_output_index_macro_micro_vdem'])

#View dataset
q1_index_macro_micro_vdem

,Unnamed: 0,country,year,country_year,index_measure,q1_macro_appointment_procedures_ind_measure,q1_micro_appointment_judges_ind_measure,q1_micro_appointment_court_presidents_ind_measure,q1_micro_appointment_veto_ind_measure,q1_macro_selection_criteria_ind_measure,...,q1_micro_judicial_self_governance_bodies_ind_measure,q1_micro_judicial_self_governance_competences_ind_measure,q1_micro_courts_administration_ind_measure,reg_id,reg_type,v2x_regime,v2x_polyarchy,reg_trans,row_regch_event,dem_ep
0,0,Albania,2000,Albania_2000,0.52,0.55,0.33,0.33,1.0,0.50,...,0.5,0.00,1.00,ALB_1914_2004,0.0,1.0,0.407,0.0,0.0,1
1,1,Albania,2001,Albania_2001,0.52,0.55,0.33,0.33,1.0,0.50,...,0.5,0.00,1.00,ALB_1914_2004,0.0,1.0,0.440,0.0,0.0,1
2,2,Albania,2002,Albania_2002,0.52,0.55,0.33,0.33,1.0,0.50,...,0.5,0.00,1.00,ALB_1914_2004,0.0,1.0,0.484,0.0,0.0,1
3,3,Albania,2003,Albania_2003,0.52,0.55,0.33,0.33,1.0,0.50,...,0.5,0.00,1.00,ALB_1914_2004,0.0,1.0,0.490,0.0,0.0,1
4,4,Albania,2004,Albania_2004,0.55,0.55,0.33,0.33,1.0,0.50,...,0.5,0.00,1.00,ALB_1914_2004,0.0,1.0,0.490,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,915,United Kingdom,2018,United Kingdom_2018,0.62,0.33,0.50,0.50,0.0,0.89,...,1.0,0.89,0.33,GBR_1919_2023,1.0,3.0,0.875,0.0,0.0,0
916,916,United Kingdom,2019,United Kingdom_2019,0.62,0.33,0.50,0.50,0.0,0.89,...,1.0,0.89,0.33,GBR_1919_2023,1.0,3.0,0.857,0.0,0.0,0
917,917,United Kingdom,2020,United Kingdom_2020,0.62,0.33,0.50,0.50,0.0,0.89,...,1.0,0.89,0.33,GBR_1919_2023,1.0,3.0,0.874,0.0,0.0,0
918,918,United Kingdom,2021,United Kingdom_2021,0.62,0.33,0.50,0.50,0.0,0.89,...,1.0,0.89,0.33,GBR_1919_2023,1.0,3.0,0.864,0.0,0.0,0
919,919,United Kingdom,2022,United Kingdom_2022,0.62,0.33,0.50,0.50,0.0,0.89,...,1.0,0.89,0.33,GBR_1919_2023,1.0,3.0,0.843,0.0,0.0,0

In [12]:
# Check data types
q1_index_macro_vdem.dtypes

Unnamed: 0                                         int64
country                                           object
year                                               int64
country_year                                      object
index_measure                                    float64
q1_macro_appointment_procedures_ind_measure      float64
q1_macro_selection_criteria_ind_measure          float64
q1_macro_professional_rights_ind_measure         float64
q1_macro_professional_obligations_ind_measure    float64
q1_macro_judicial_administration_ind_measure     float64
reg_id                                            object
reg_type                                         float64
v2x_regime                                       float64
v2x_polyarchy                                    float64
reg_trans                                        float64
row_regch_event                                  float64
dem_ep                                             int64
dtype: object